# Generated by Django 4.2.1 on 2023-06-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTLV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default='img/logo.svg', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='060200564623', max_length=50),
        ),
    ]
