# Generated by Django 4.2.1 on 2023-06-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTLV', '0002_alter_producto_imagen_alter_producto_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='060201004923', max_length=50),
        ),
    ]
