# Generated by Django 4.2.1 on 2023-06-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTLV', '0005_alter_pedido_orden_alter_producto_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='20230602011048', max_length=50),
        ),
    ]
