# Generated by Django 4.2.1 on 2023-06-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTLV', '0006_alter_producto_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='20230602111728', max_length=50),
        ),
    ]
